title: "Un Monde de Données : Mes Projets, Mes Analyses"
show_downloads: TRUE
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
